# Official Node.js image as the base image for development
FROM node:18 as development

# Set the working directory inside the container
WORKDIR /app

# Install Node.js dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy the entire Next.js application to the working directory
COPY . .

# Expose the port that Next.js will listen on during development
EXPOSE 3000

# Start the Next.js development server with hot refresh
CMD ["npm", "run", "dev"]