version: "3.9"

services:
  nextjs:
    build:
      context: ./client
      dockerfile: Dockerfile.development
    env_file:
      - .env.development
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app

  django:
    build:
      context: ./api
      dockerfile: Dockerfile.development
    ports:
      - "8000:8000"
    env_file:
      - .env.development
    environment:
      CREATE_SUPERUSER: yes
    volumes:
      - ./api:/app

  db:
    image: postgres:15.2-alpine
    env_file:
      - .env.development
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}

  redis:
    image: redis:6.2.7-alpine

  celery:
    build:
      context: ./api
      dockerfile: Dockerfile.development
    command: celery -A django worker -l info
    env_file:
      - .env.development
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      - db
      - redis

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    env_file:
      - .env.development
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.com
      PGADMIN_DEFAULT_PASSWORD: 12345678
    depends_on:
      - db

  flower:
    image: mher/flower
    ports:
      - "5555:5555"
    env_file:
      - .env.development
    depends_on:
      - celery
